In [ ]:
a=np.array([[1,2,3,4],[1,2,3,4]])
print(a[1][0])

1


In [8]:
!pip install nbformat

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])
print(a)


[[1 2 3]
 [4 5 6]]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.ndim)
print(a.size)


(2, 3)
2
6


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
a = np.array([10,20,30])
print(a[0])


10


In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])
print(a[1][2])
print(a[1:4])
print(a.sum())
a.min()

6
[[4 5 6]]
21


np.int64(1)

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print('Last element from 2nd dim: ', arr[1, -1])



2nd element on 1st row:  2
Last element from 2nd dim:  10


Negative Slicing

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[5 6]
[2 4]
[1 3 5 7]


In [ ]:
import numpy as np

b = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(b[0, 1:4:2])
print(b[0:2, 2])

print(b[0:2, 1:4])



[2 4]
[3 8]
[[2 3 4]
 [7 8 9]]


In [ ]:
import numpy as np
b = np.array([1, 2, 3, 4])
print(b.dtype)#numbers are stored as 64-bit integers.

int64


In [ ]:
import numpy as np
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype) #Unicode string

<U6


Meaning:

< little endian

U Unicode

6 max 6 characters

Because "banana" and "cherry" have 6 letters.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

x = arr.view()
arr[0] = 42

print(arr)
print(x)


In [ ]:
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
['apple' 'banana' 'cherry']


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)


(2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new = arr.reshape(4, 3)
print(new)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)


1
2
3


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)


for x in arr:
  for y in x:
    print(y)


[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [ ]:

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)


[1 2 3 4 5 6]


In [ ]:

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)


[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
import numpy as n
print(n.__version__)
a=n.array([1,2,3])
print(a)
for i in range(len(a)):
  print(a[i])
  print(a[:i])
print(a.size)
print(a.ndim)
print(a.shape)
print(a[0]+a[1])


2.0.2
[1 2 3]
1
[]
2
[1]
3
[1 2]
3
1
(3,)
3


In [ ]:
#2d array
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a[0,1])
print(a.sum())
print(a.min())
print(a.max())
print(a.mean())
print(a.std())
print(a.var())
print(a.prod())
print(a.cumsum())
print(a.cumprod())
print(a.argmin())
print(a.argmax())
print(a.argsort())
print(a.reshape(3,2))
print(a.T)
print(a.flatten())
print(a.tolist())

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
2
21
1
6
3.5
1.707825127659933
2.9166666666666665
720
[ 1  3  6 10 15 21]
[  1   2   6  24 120 720]
0
5
[[0 1 2]
 [0 1 2]]
[[1 2]
 [3 4]
 [5 6]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1, 2, 3], [4, 5, 6]]


In [ ]:
a

In [ ]:
print(n.zeros((3,3)))
print(n.ones((3,3)))
print(n.eye(3))
print(n.random.rand(3,3))
print(n.random.randn(3,3))
print(n.random.randint(1,10,3))
print(n.arange(1,10,2))
print(n.linspace(1,10,3))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.98194478 0.6788252  0.18280705]
 [0.9475853  0.61066912 0.5943673 ]
 [0.55647943 0.87265046 0.96146375]]
[[ 0.61140454 -1.18373057 -0.83205641]
 [ 0.94751418  2.45482937 -0.37018861]
 [-0.94762434 -0.53874866  2.48918383]]
[8 6 7]
[1 3 5 7 9]
[ 1.   5.5 10. ]
