In [35]:
!pip install nbformat

#Multiple regression From Scratch using **Gradient Descent**

# 🌸 Multiple Linear Regression using Gradient Descent (Full Derivation)

We will derive everything step by step:

1. Model equation  
2. Cost function  
3. Matrix form  
4. Derivative step-by-step  
5. Gradient formula  
6. Final update rule  

Very simple and clear.

---

# 🌸 STEP 1: Model (Start From Basic)

For multiple regression:

$$
\hat{y} = b_0 + b_1 x_1 + b_2 x_2 + \dots + b_n x_n
$$

In matrix form:

$$
\hat{Y} = X\beta
$$

Where:

- $X$ = input matrix  
- $\beta$ = weight vector  
- $\hat{Y}$ = predicted output  

---

# 🌸 STEP 2: Define Error

For one data point:

$$
\text{error} = y - \hat{y}
$$

For all data:

$$
E = Y - X\beta
$$

---

# 🌸 STEP 3: Cost Function (Mean Squared Error)

We square the error to remove negatives:

$$
J(\beta) = \frac{1}{2n} \sum (y - \hat{y})^2
$$

Why $\frac{1}{2}$?

Because when we differentiate, 2 cancels.  
It makes math simpler.

Matrix form:

$$
J(\beta) = \frac{1}{2n} (Y - X\beta)^T (Y - X\beta)
$$

This is the function we want to minimize.

---

# 🌸 STEP 4: Expand the Cost Function

Let:

$$
E = Y - X\beta
$$

So:

$$
J = \frac{1}{2n} E^T E
$$

Substitute:

$$
J = \frac{1}{2n} (Y - X\beta)^T (Y - X\beta)
$$

Now expand transpose:

$$
(Y - X\beta)^T = Y^T - \beta^T X^T
$$

Multiply:

$$
J = \frac{1}{2n} \left[ Y^T Y - Y^T X\beta - \beta^T X^T Y + \beta^T X^T X \beta \right]
$$

Important identity:

$$
Y^T X\beta = \beta^T X^T Y
$$

So combine terms:

$$
J = \frac{1}{2n} \left[ Y^T Y - 2\beta^T X^T Y + \beta^T X^T X \beta \right]
$$

---

# 🌸 STEP 5: Take Derivative with respect to $\beta$

Derivative rules:

1. Derivative of constant → 0  
2. Derivative of $\beta^T A$ → $A$  
3. Derivative of $\beta^T A \beta$ → $2A\beta$  

Now differentiate each term:

- $Y^T Y$ → constant → 0  
- $-2\beta^T X^T Y$ → becomes $-2X^T Y$  
- $\beta^T X^T X \beta$ → becomes $2X^T X \beta$

So gradient becomes:

$$
\nabla J = \frac{1}{2n} (-2X^T Y + 2X^T X \beta)
$$

Cancel 2:

$$
\nabla J = \frac{1}{n} (X^T X \beta - X^T Y)
$$

Factor:

$$
\nabla J = \frac{1}{n} X^T (X\beta - Y)
$$

---

# 🎯 FINAL GRADIENT FORMULA

$$
\boxed{\nabla J = \frac{1}{n} X^T (X\beta - Y)}
$$

This is the most important result.

---

# 🌸 STEP 6: Gradient Descent Update Rule

Gradient Descent rule:

$$
\beta = \beta - \alpha \nabla J
$$

Substitute gradient:

$$
\beta = \beta - \alpha \left( \frac{1}{n} X^T (X\beta - Y) \right)
$$

Where:

- $\alpha$ = learning rate  
- $n$ = number of samples  

---

# 🌸 Final Algorithm

1. Initialize $\beta$ randomly  
2. Compute prediction:

$$
\hat{Y} = X\beta
$$

3. Compute gradient:

$$
\nabla J = \frac{1}{n} X^T (X\beta - Y)
$$

4. Update:

$$
\beta = \beta - \alpha \nabla J
$$

5. Repeat until convergence  

---

# 🌸 Intuition

- $(X\beta - Y)$ → error vector  
- Multiply by $X^T$ → spreads error to weights  
- Divide by $n$ → take average  
- Subtract → move toward minimum  

---

# 🌸 Why This Works?

The cost function is convex (bowl-shaped).  
Gradient points upward.  
Subtracting gradient moves downward.  
Eventually, we reach the global minimum.

---

# 🌸 Connection to Normal Equation

If we set gradient to zero:

$$
X^T (X\beta - Y) = 0
$$

Then:

$$
X^T X \beta = X^T Y
$$

So:

$$
\beta = (X^T X)^{-1} X^T Y
$$

Gradient Descent and Normal Equation give the same final solution.

---

You have now fully derived Multiple Linear Regression using calculus.

This is real ML foundation 💛

###BATCH GRADIENT DESCENT

In [10]:
import numpy as np
X = np.array([
    [1, 2],
    [2, 1],
    [3, 3],
    [4, 5],
    [5, 4]
])

In [11]:
y = np.array([8, 7, 15, 23, 22])
ones = np.ones((X.shape[0], 1))
X = np.hstack((ones, X))
y = y.reshape(-1, 1)


In [12]:
X

array([[1., 1., 2.],
       [1., 2., 1.],
       [1., 3., 3.],
       [1., 4., 5.],
       [1., 5., 4.]])

In [14]:
y

array([[ 8],
       [ 7],
       [15],
       [23],
       [22]])

In [26]:
n, p = X.shape
beta = np.zeros((p, 1))    # Initialize weights
alpha = 0.01               # Learning rate
epochs = 1000

In [27]:
for i in range(epochs):

    y_pred = X @ beta

    # Gradient formula
    gradient = (1/n) * (X.T @ (y_pred - y))

    # Update rule
    beta = beta - alpha * gradient
    cost = (1/(2*n)) * np.sum((y_pred - y)**2)
    if i % 100 == 0:
         print("Epoch:", i, "Cost:", cost)



Epoch: 0 Cost: 135.1
Epoch: 100 Cost: 0.07226813255700028
Epoch: 200 Cost: 0.04000446755518486
Epoch: 300 Cost: 0.023447562351446696
Epoch: 400 Cost: 0.014509009677707472
Epoch: 500 Cost: 0.009403127346784917
Epoch: 600 Cost: 0.006317637048643777
Epoch: 700 Cost: 0.0043568550389750434
Epoch: 800 Cost: 0.0030589990156156556
Epoch: 900 Cost: 0.0021734104147980967


In [17]:
beta


array([[0.57340658],
       [2.25465554],
       [2.58487297]])

In [18]:
x_new = np.array([[1, 6, 3]])  # 1 for intercept
prediction = x_new @ beta

print("Prediction for x1=6, x2=3:", prediction[0][0])

Prediction for x1=6, x2=3: 21.855958756944236


###STOCHASTIC GRADIENT DESCENT

In [1]:
import numpy as np

# Dataset
X = np.array([
    [1, 2],
    [2, 1],
    [3, 3],
    [4, 5],
    [5, 4]
])

y = np.array([8, 7, 15, 23, 22])

# Add intercept
ones = np.ones((X.shape[0], 1))
X = np.hstack((ones, X))
y = y.reshape(-1, 1)

n, p = X.shape
beta = np.zeros((p, 1))

alpha = 0.01
epochs = 1000

for epoch in range(epochs):

    for i in range(n):

        xi = X[i].reshape(1, -1)
        yi = y[i].reshape(1, -1)

        y_pred = xi @ beta

        gradient = xi.T @ (y_pred - yi)

        beta = beta - alpha * gradient

print("Stochastic GD Beta:")
print(beta)

Stochastic GD Beta:
[[1.60895372e-04]
 [1.99997435e+00]
 [2.99998617e+00]]


###MINI BATCH GRADIENT DESCENT

In [2]:
import numpy as np

# Dataset
X = np.array([
    [1, 2],
    [2, 1],
    [3, 3],
    [4, 5],
    [5, 4]
])

y = np.array([8, 7, 15, 23, 22])

# Add intercept
ones = np.ones((X.shape[0], 1))
X = np.hstack((ones, X))
y = y.reshape(-1, 1)

n, p = X.shape
beta = np.zeros((p, 1))

alpha = 0.01
epochs = 1000

for epoch in range(epochs):

    for i in range(n):

        xi = X[i].reshape(1, -1)
        yi = y[i].reshape(1, -1)

        y_pred = xi @ beta

        gradient = xi.T @ (y_pred - yi)

        beta = beta - alpha * gradient

print("Stochastic GD Beta:")
print(beta)

Stochastic GD Beta:
[[1.60895372e-04]
 [1.99997435e+00]
 [2.99998617e+00]]
