In [1]:
!pip install nbformat

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score

# --------------------------------
# 1. Load dataset from seaborn
# --------------------------------

df = sns.load_dataset("titanic")

print(df.head())

# --------------------------------
# 2. Select useful features
# --------------------------------

df = df[['survived','pclass','sex','age','fare']]

# remove missing values
df = df.dropna()

# convert categorical to numeric
df['sex'] = df['sex'].map({'male':0,'female':1})

# --------------------------------
# 3. Split features and target
# --------------------------------

X = df[['pclass','sex','age','fare']]
y = df['survived']

# --------------------------------
# 4. Train Test Split
# --------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# --------------------------------
# 5. Train Logistic Regression
# --------------------------------

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

# --------------------------------
# 6. Predictions
# --------------------------------

y_pred = model.predict(X_test)

# --------------------------------
# 7. Evaluation Metrics
# --------------------------------

cm = confusion_matrix(y_test, y_pred)

precision = precision_score(y_test, y_pred)

recall = recall_score(y_test, y_pred)

f1 = f1_score(y_test, y_pred)

accuracy = accuracy_score(y_test, y_pred)

# --------------------------------
# 8. Print Results
# --------------------------------

print("\nConfusion Matrix:\n", cm)

print("\nPrecision:", precision)

print("Recall:", recall)

print("F1 Score:", f1)

print("Accuracy:", accuracy)

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  

Confusion Matrix:
 [[68 19]
 [16 40]]

Precision: 0.6779661016949152
Recall: 0.7142857142857143
F1 Score: 0.6956521739130435
Accuracy: 0.7552447552447552


In [2]:
import seaborn as sns
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score

# --------------------------------
# 1. Load dataset from seaborn
# --------------------------------

df = sns.load_dataset("iris")

print(df.head())

# --------------------------------
# 2. Convert target to yes/no/maybe
# --------------------------------

df["target"] = df["species"].map({
    "setosa": "yes",
    "versicolor": "no",
    "virginica": "maybe"
})

# features
X = df.drop(columns=["species","target"])

# target
y = df["target"]

# --------------------------------
# 3. Train test split
# --------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# --------------------------------
# 4. Train Logistic Regression
# --------------------------------

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

# --------------------------------
# 5. Predictions
# --------------------------------

y_pred = model.predict(X_test)

# --------------------------------
# 6. Metrics
# --------------------------------

cm = confusion_matrix(y_test, y_pred)

precision = precision_score(y_test, y_pred, average="macro")
recall = recall_score(y_test, y_pred, average="macro")
f1 = f1_score(y_test, y_pred, average="macro")
accuracy = accuracy_score(y_test, y_pred)

# --------------------------------
# 7. Print Results
# --------------------------------

print("\nConfusion Matrix:\n", cm)

print("\nPrecision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Accuracy:", accuracy)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Confusion Matrix:
 [[11  0  0]
 [ 0  9  0]
 [ 0  0 10]]

Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Accuracy: 1.0
